export type TimesheetStatus = 'DRAFT' | 'SUBMITTED' | 'APPROVED' | 'REJECTED' | 'EXPORTED';

export interface TimesheetEntry {
  id: number;
  workOrderId: number;
  workDate: string;
  clientName: string;
  siteAddress: string | null;
  city: string | null;
  state: string | null;
  zip: string | null;
  miles: number | null;
  onsiteStartTime: string | null;
  breakStartTime: string | null;
  breakEndTime: string | null;
  offsiteEndTime: string | null;
  comments: string | null;
  autoGenerated: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface Timesheet {
  id: number;
  technicianId: number;
  technicianName: string;
  weekStartDate: string;
  weekEndDate: string;
  status: TimesheetStatus;
  submittedAt: string | null;
  approvedAt: string | null;
  technicianSignatureText: string | null;
  createdAt: string;
  updatedAt: string;
  entries: TimesheetEntry[];
}

export interface TimesheetEntryUpdate {
  miles: number | null;
  onsiteStartTime: string | null;
  breakStartTime: string | null;
  breakEndTime: string | null;
  offsiteEndTime: string | null;
  comments: string | null;
}

export interface TimesheetFilters {
  weekStart?: string;
  technicianId?: number | null;
  status?: TimesheetStatus | '';
}
